services:
  saas-postgres:
    container_name: "saas-postgres"
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - /opt/saas/data/postgres:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432