services:
  saas-postgres:
    container_name: "saas-postgres"
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - /opt/saas/data/postgres:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  saas-redis:
    container_name: "saas-redis"
    image: redis:7.4
    restart: always
    ports:
      - 6379:6379

  saas-mongo:
    container_name: "saas-mongo"
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  rabbitmq:
    container_name: "saas-rabbitmq"
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: password
